### ISSUE TITLE
[Feature Request] Package Filter

### ISSUE THREAD

**Issue by zhaolinlau** [pulsar-edit/package-backend#201] opened 2023-09-18 16:37 UTC
**Is this feature Currently Implemented in any way with the upstream API Server**
- [] Yes
- [x] No

**Is your feature request related to a problem? Please describe.**
Kinda hard to know which package is recently updated, added, most downloads, most stars

**Describe the solution you'd like**
Able to search package by filtering with recently updated, added, most downloads, most stars

**Comment by Daeraxa** [comment] 2023-09-18 18:25
I think we have this one covered already on [package-frontend](https://github.com/pulsar-edit/package-frontend/pull/77). Just needs some attention which it hasn't seen in a while.

**Comment by confused-Techie** [comment] 2023-09-18 23:15
So this feature absolutely already exists. It just isn't exposed via some nice UI anywhere at the moment.

But looking at the [API Definition](https://github.com/pulsar-edit/package-backend/blob/main/docs/reference/API_Definition.md) (Also our live public [swagger instance](https://api.pulsar-edit.dev/swagger-ui/) if you are into that sort of thing)

We can see that (depending on some endpoints) we are already able to filter and organize packages:

* Sort Packages:
    - downloads
    - created_at
    - updated_at
    - stars
    - relevance (Only works on the search endpoints)
* Direction of packages:
    - descending
    - ascending
* Filter Packages (Only on the main `/api/packages` endpoint)
     - service
     - serviceType
     - serviceVersion
     - fileExtension

So I feel like we have covered everything, being able to sort by nearly every value, order them how preferred, and as for the features that we made (As in they weren't implemented originally in Atom's backend) we can filter our results to only include grammars that support a specific file extension, or for the service it provides or consumes, or even for packages that support specific versions of a service.

So I think we have got this one covered. Otherwise as a request for this to be available in a nice UI on the website, then this issue is a duplicate of [`package-frontend#48`](https://github.com/pulsar-edit/package-frontend/issues/48) that's been attempted to be implemented in [`package-frontend#77`](https://github.com/pulsar-edit/package-frontend/pull/77).

---

So appreciate you contributing @zhaolinlau but I'll close this one out.

If you have any suggestions or ideas for this feature, I'd go ahead and comment further on either the issue or PR linked above.

---

I'll add if you want to use these features today, feel free to ask, or reference the API documentation, and all query parameters are supported in the frontend site already, so appending them manually into the URL will get you the results requested.

Such as:

* Show only packages that provide a grammar that supports file extension `js`: `https://web.pulsar-edit.dev/packages?fileExtension=js`
* Show only packages that `provide` for the service `autocomplete.provider` (Packages that provide autocompletions): `https://web.pulsar-edit.dev/packages?serviceType=provided&service=autocomplete.provider`
* The same as above, but order by the most recently updated packages: `https://web.pulsar-edit.dev/packages?serviceType=provided&service=autocomplete.provider&sort=updated_at`

**Closed by confused-Techie** 2023-09-18 23:15 UTC
Labels: enhancement
