### ISSUE TITLE
[BUG] This Page encountered an Error! Sorry!

### ISSUE THREAD

**Issue by zhaolinlau** [pulsar-edit/package-backend#200] opened 2023-09-10 04:22 UTC
**Is this Bug Present in the upstream API Server?**
- [x] Yes
- [ ] No
- [ ] Unsure

**What is the Bug**
Most of the package links cannot be accessed

**How to Replicate the Bug**
1. browse https://web.pulsar-edit.dev/
2. click any of the packages
3. then it will say "This Page encountered an Error! Sorry!"
![image](https://github.com/pulsar-edit/package-backend/assets/68846168/9f855ec3-3f2a-4535-ba99-aebabb6204c3)

**Comment by confused-Techie** [comment] 2023-09-10 22:14
Thanks a ton for reporting this.

This is an error we have seen once before, where our autoscaling cluster of instances will create on bad instance. Essentially creating the chance that anyone that happens to be connected to that bad instance will have every single page fail. Meanwhile every other instance is still healthy, so to others there is no issue.

The problem does eventually resolve itself once there is low usage and the instance is killed, which is exactly what's happened in this case. 

But as we currently have no idea what causes this to happen, or how we can fix it, I'll go ahead and leave this issue open until we are able to do something to mitigate this issue.

Thanks a ton for reporting this!

**Comment by confused-Techie** [comment] 2023-12-31 00:47
While the root cause of this issue hasn't been totally addressed, since the implementation of improved error handling, and providing much better logging, as well as returning errors to the user in a better way has been added, I'll go ahead and close this one for now.

While the root cause of this issue may still appear, we will now be much more equipped to actually solve it, and I feel like this is the best place for us to close this issue, since it's possible the issue may not return.

Thanks a ton again for reporting this, resolve via [`pulsar-edit/package-frontend#123`](https://github.com/pulsar-edit/package-frontend/pull/123)

**Closed by confused-Techie** 2023-12-31 00:47 UTC
Labels: bug
