### ISSUE TITLE
Package with severely malformed data: web-developer-tools

### ISSUE THREAD

**Issue by manngo** [pulsar-edit/package-backend#125] opened 2023-03-18 01:00 UTC
I have a package from the old Atom days, which I have tried to migrate to Pulsar.

On my own setup I can’t update to the latest version, and when I try to view it on the https://web.pulsar-edit.dev/packages/ site I get the following message:

>[web-developer-tools](https://web.pulsar-edit.dev/packages/web-developer-tools)
>
>Whoops! Seems this package has severly malformed data. Please submit an issue to https://github.com/pulsar-edit/package-backend/issue with the package's name. Thank you!

What is my next step?

PS I think there are two further issues with the message: the spelling of “severely” and the reference which (a) isn’t a link and (b) references `/issue` instead of `/issues`.

**Comment by confused-Techie** [comment] 2023-03-18 20:38
Thanks for reporting this issue.
Seems this is partially a duplicate of #88 

But as that one hasn't been gotten to yet I appreciate you calling out this issue again. I've already created a PR to submit a fix for the warning given, and will take a look at the malformed data today hopefully. As that will require a manual edit to the database.

Essentially for a short period of time ( a few months ago I think) there was a bug that would incorrectly write data to the database when attempting to update a package. Which seems affected this one

**Comment by confused-Techie** [comment] 2023-03-18 20:52
So when investigating this to resolve the issue on the database, I've hit a bit of a roadblock.

The latest version the server has is `web-developer-tools` version `0.4.4` but the repo [`manngo/atom-web-tools`](https://github.com/manngo/atom-web-tools) only has up to version `0.4.0`.

Would you like me to reset the latest version on the backend to `0.4.0`? Otherwise I can fix the malformed data and have it point to `0.4.4` still but nobody will be able to install the package. @manngo how would you like to proceed? 

Additionally you could manually publish a new `0.4.4` tag on GitHub and I can manually apply the fixes to use that as the latest on the database

**Comment by confused-Techie** [comment] 2023-03-25 21:49
With no response from the author, I've gone ahead and resolved this issue by falling back to `0.4.0` version of their package. Since there was no valid way to keep the `0.4.4` version as they had removed the tag from GitHub.

So I've deleted the now broken metadata for version `0.4.4` of their package, and fixed the metadata of their package as a whole. Since this was broken by a bug in the backend, the packages metadata has been fixed to properly include all associated data, taken from their GitHub repo.

Thanks for letting me know about this @manngo and hope this fix works for you.

**Closed by confused-Techie** 2023-03-25 21:49 UTC
